"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarFB from "@/components/UI/NavbarFB";
import HeaderContent from "@/components/UI/HeaderContent";
import { usePathname } from "next/navigation";
import { GlobalStateProvider } from "@/contexts/GlobalStateContext";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <AuthProvider>
      <GlobalStateProvider>
        <html lang="es" suppressHydrationWarning={true}>
          <body className={inter.className}>
            <NavbarFB />
            <div className="pt-14 md:pt-12">
              {pathname !== "/" && <HeaderContent />}
              {pathname !== "/" && (
                <div className="flex gap-8 items-center container mx-auto mt-4">
                  <div className="flex-1 hidden md:block">
                    <img
                      src="/images/promocion_huancaro w900.png"
                      alt="imagen feria de Huancaro"
                      className="w-full rounded-3xl"
                    />
                  </div>
                  <div className="flex-1 h-fit">{children}</div>
                </div>
              )}
              {pathname == "/" && children}
            </div>
          </body>
        </html>
      </GlobalStateProvider>
    </AuthProvider>
  );
}
